# 熵权法
## 介绍
无论是层次分析法或是Topsis法，都需要对数据参数的权重进行设计，而在上述方法中获取的权重都是主观得到的。在一些特定情况下，我们需要**重点获取与其他项不同的权重**

熵权法可以以参数的指标的混乱程度（信息熵）来确定参数的权值

**数据的变异程度越小，所包含的信息越少**

In [1]:
import numpy as np

def mylog(p):
    n=len(p)
    logp=np.zeros(n) #创造一个n维的0向量
    for i in range(n):
        if p[i]==0:
            logp[i]=0 
        else:
            logp[i]=np.log(p[i])
    return logp

X=np.array([[0.1,0.2,0.3,0.4],[1,2,3,4],[0.01,0.02,0.03,0.04]])

Z=X/ np.sqrt(np.sum(X**2,axis=0)) #axis=0表示按列求和

print(Z) #输出归一化后的矩阵

n,m=Z.shape
D=np.zeros(m) #创造一个m维的0向量
for i in range(m):
    x=Z[:,i] #取出Z的第i列
    p=x/np.sum(x) #计算x的概率分布 
    e=-np.sum(p*mylog(p))/np.log(n)#计算熵 
    D[i]=1-e #计算相对熵

print(D) #输出相对熵
W=D/np.sum(D) #计算权重
print(W) #输出权重


[[0.09949879 0.09949879 0.09949879 0.09949879]
 [0.99498793 0.99498793 0.99498793 0.99498793]
 [0.00994988 0.00994988 0.00994988 0.00994988]]
[0.67842328 0.67842328 0.67842328 0.67842328]
[0.25 0.25 0.25 0.25]
